name: Debug
on:
  workflow_dispatch

jobs:
  example-job:
      runs-on: ubuntu-latest
      steps:
        - name: path
          run: echo -n "path ${{ secrets.SERVER_PATH }}" >> foo && cut -c1-3 foo && cut -c4
        - name: host
          run: echo -n "server ${{ secrets.SERVER }}" >> foo && cut -c1-3 foo && cut -c4
        - name: key
          run: echo -n "key ${{ secrets.SERVER_KEY }}" >> foo && cut -c1-3 foo && cut -c4
        
