name: Build & Release

on:
    push:
        tags:
            - '*'

jobs:
    release:
        uses: gollenia/github-actions/.github/workflows/wordpress-release.yml@master
        with:
            tag: ${{ github.ref_name }}
